version: '3'

networks:
  openuu-net:
    external: false

services:
  account:
    container_name: openuu-account
    image: openuu-server:latest
    command: openuu-account
    environment:
      OPENUU_ACCOUNT_BIND: 0.0.0.0:21114
    ports:
      - "127.0.0.1:21114:21114"
    volumes:
      - ./data:/root
    networks:
      - openuu-net
    restart: unless-stopped

  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: openuu-server:latest
    command: hbbs -r openuu.example.com:21117
    volumes:
      - ./data:/root
    networks:
      - openuu-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: openuu-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - openuu-net
    restart: unless-stopped
