#!/bin/sh

# PROVIDE: openuu_hbbs
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# openuu_hbbs_enable (bool):            Set to NO by default.
#               Set it to YES to enable openuu_hbbs.
# openuu_hbbs_ip (string):              Set IP address/hostname of relay server to use
#               Defaults to "127.0.0.1", please replace with your server hostname/IP.
# openuu_hbbs_args (string):            Set extra arguments to pass to openuu_hbbs
#               Default is "-r ${openuu_hbbs_ip} -k _".
# openuu_hbbs_user (string):            Set user that openuu_hbbs will run under
#               Default is "root".
# openuu_hbbs_group (string):           Set group that openuu_hbbs will run under
#               Default is "wheel".

. /etc/rc.subr

name=openuu_hbbs
desc="OpenUU ID/Rendezvous Server"
rcvar=openuu_hbbs_enable

load_rc_config $name

: ${openuu_hbbs_enable:=NO}
: ${openuu_hbbs_ip:=127.0.0.1}
: ${openuu_hbbs_args="-r ${openuu_hbbs_ip} -k _"}
: ${openuu_hbbs_user:=openuu}
: ${openuu_hbbs_group:=openuu}

pidfile=/var/run/openuu_hbbs.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/hbbs
openuu_hbbs_chdir=/var/db/openuu-server
command_args="-p ${pidfile} -o /var/log/openuu-hbbs.log ${procname} ${openuu_hbbs_args}"
## If you want the daemon to do its log over syslog, comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${openuu_hbbs_args}"

start_precmd=openuu_hbbs_startprecmd

openuu_hbbs_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${openuu_hbbs_user}:${openuu_hbbs_group} ${pidfile};
    else
        install -o ${openuu_hbbs_user} -g ${openuu_hbbs_group} /dev/null ${pidfile};
    fi
    if [ -e ${openuu_hbbs_chdir} ]; then
        chown -R ${openuu_hbbs_user}:${openuu_hbbs_group} ${openuu_hbbs_chdir};
        chmod -R 770 ${openuu_hbbs_chdir};
    else
        mkdir -m 770 ${openuu_hbbs_chdir};
        chown ${openuu_hbbs_user}:${openuu_hbbs_group} ${openuu_hbbs_chdir};
    fi
    if [ -e /var/log/openuu-hbbs.log ]; then
        chown -R ${openuu_hbbs_user}:${openuu_hbbs_group} /var/log/openuu-hbbs.log;
        chmod 660 /var/log/openuu-hbbs.log;
    else
        install -o ${openuu_hbbs_user} -g ${openuu_hbbs_group} /dev/null /var/log/openuu-hbbs.log;
        chmod 660 /var/log/openuu-hbbs.log;
    fi
}

run_rc_command "$1"
